Added limited access app type to docs
box/developer.box.com pull request #171
Opened 2020-11-04 23:57 UTC by knmeiss

# Description

This added in the limited access app type, which is part of the new app creation flow. 

Fixes DDOC-375

## Checklist

- [ X] My code follows the style guidelines of this project
- [X ] I have performed a self-review of my own changes
- [ X] I have run `yarn lint` to make sure my changes pass all linters
- [ X] I have pulled the latest changes from the upstream developer branch

## Contribution guidelines

For contribution guidelines, styleguide, and other helpful information please
see the `CONTRIBUTING.md` file in the root of this project.

2020-11-06 15:19 UTC, jcleblanc commented on content/guides/applications/custom-apps/app-token-setup.md
> +tab for your application within the[Developer console][devconsole].
Add space before the Developer console link

2020-11-06 15:35 UTC, jcleblanc commented on content/guides/applications/custom-apps/jwt-setup.md
> +Then, navigate to configuration tab for your application in the
Recommend changing "navigate to configuration tab..." to "navigate to **the** configuration tab..."

2020-11-06 15:35 UTC, jcleblanc commented on content/guides/applications/custom-apps/jwt-setup.md
> +[Developer console][devconsole]and scroll down to the
Add space after developer console link

2020-11-06 15:42 UTC, jcleblanc commented on content/guides/applications/custom-apps/jwt-setup.md
> +Before the application can be used, some additional, basic configuration is
This reads a little strange to me (the old sentence does too). Perhaps just cut it down to "Before the application can be used, some additional configuration is required".

2020-11-06 16:09 UTC, jcleblanc requested changes
Just a few small tweaks, but otherwise lgtm

2020-11-06 16:09 UTC, jcleblanc commented on content/guides/applications/custom-skills/setup.md
> +To set up the Invocation URL, navigate to the ** Configuration** tab of the
Remove the space in ** Configuration** - looks like it's not resolving into bold text.

2020-11-06 16:09 UTC, jcleblanc commented on content/guides/applications/custom-skills/setup.md
> +Fill in a secure HTTPs address and save the form. The invocation URL is now
Two items: Let's capitalize HTTPS for consistency (HTTPs -> HTTPS) and for the last sentence, recommend changing it to "The invocation URL is now configured." (drop **been**)

2020-11-06 22:04 UTC, knmeiss commented on content/guides/applications/custom-skills/setup.md
> +![App name form](../images/skill-name.png)
moved file so I could keep this url

2020-11-09 16:20 UTC, jcleblanc approved these changes

2020-11-09 16:22 UTC, merged