Ddoc 596 cli updates
box/developer.box.com pull request #335
Opened 2022-05-31 23:57 UTC by Smartoneinok

PR for 596 - Please confirm with Alex before releasing even though he is on Pat leave!

2022-06-21 16:25 UTC, bszwarc requested changes
I added some comments and suggestions - of course they are just suggestions, and you decide if you want to keep them. Some of them can be applied and committed right away, and some are some structural suggestions :)

2022-06-21 16:25 UTC, bszwarc commented on content/guides/tooling/cli/quick-start/0-index.md
> +5. Explore using [Powershell scripts with the CLI][five]
I miss the info about what should be explored - for example `Explore automation using Powershell scripts`

2022-06-21 16:25 UTC, bszwarc commented on content/guides/tooling/cli/quick-start/5-powershell-script-templates.md
> +# Using Powershell Scripts with the Box CLI
```suggestion
# Using PowerShell Scripts with the Box CLI
```

2022-06-21 16:25 UTC, bszwarc commented on content/guides/tooling/cli/quick-start/5-powershell-script-templates.md
> +By itself, the CLI is already powerful, but using it alongside a Powershell
```suggestion
By itself, the CLI is already powerful, but using it alongside a PowerShell
```

2022-06-21 16:25 UTC, bszwarc commented on content/guides/tooling/cli/quick-start/5-powershell-script-templates.md
> +### Configure a Box application
```suggestion
### Configured Box application
```

2022-06-21 22:08 UTC, barduinor commented on content/guides/tooling/cli/quick-start/5-powershell-script-templates.md
> +user provisioning and folder creation [script][script-1]
done

2022-06-21 22:19 UTC, barduinor commented on content/guides/tooling/cli/quick-start/5-powershell-script-templates.md
> +You must adapt this script for your own environment.
to run in

2022-06-21 22:20 UTC, barduinor commented on content/guides/tooling/cli/quick-start/5-powershell-script-templates.md
> +### CSV Files
we are not actually uploading users, we are preparing the csv files. humm user list?

2022-06-21 22:36 UTC, barduinor commented on content/guides/tooling/cli/quick-start/5-powershell-script-templates.md
> +scripts path per the configurations you specified in `Users_Create_Provision.ps1`:
no, it depends where did the user pointed the paths in the script

2022-06-23 14:01 UTC, bszwarc reviewed
A couple of minor comments :)

2022-06-23 14:01 UTC, bszwarc commented on content/guides/tooling/cli/quick-start/5-powershell-script-templates.md
> +- or, optionally,  create the folder structure by uploading from a local drive
```suggestion
- or, optionally, create the folder structure by uploading from a local drive
```
unnecessary space :)

2022-06-23 14:14 UTC, bszwarc commented on content/guides/tooling/cli/quick-start/5-powershell-script-templates.md
> +`Employeess_1.csv` with the following data:
```suggestion
`Employees_1.csv` with the following data:
```

2022-06-23 14:16 UTC, bszwarc commented on content/guides/tooling/cli/quick-start/5-powershell-script-templates.md
> +file you would like to load. For example, `Employee_1.csv`:
```suggestion
file you would like to load. For example, `Employees_1.csv`:
```

2022-06-23 15:32 UTC, bszwarc approved these changes

2022-06-23 15:40 UTC, merged