Annotations in preview
box/developer.box.com pull request #382
Opened 2022-10-14 15:27 UTC by superojla

Documentation updates for V4 annotations in content preview.

Fixes #[DDOC-647](https://jira.inside-box.net/browse/DDOC-647)

2022-10-17 16:46 UTC, greg-in-a-box requested changes
Left some comments

2022-10-17 16:46 UTC, greg-in-a-box commented on content/guides/embed/ui-elements/preview.md
> +2. Run `npm i box-ui-elements@15.0.0` to install [BUIE][buie] version with
```suggestion
2. Run `npm i box-ui-elements@16.0.0` to install [BUIE][buie] version with
```

We are going to release BUIE 16 to include these changes, 15 is the current major release

2022-10-17 16:46 UTC, greg-in-a-box commented on content/guides/embed/ui-elements/preview.md
> +the latest version of box-annotations
```suggestion
// You may see one already from legacy annotations if you do not dynamically
load the latest version of box-annotations
```

2022-10-17 16:46 UTC, greg-in-a-box commented on content/guides/embed/ui-elements/preview.md
> +                    }
This is undocumented but we use it internally, this may or may not change in future releases

2022-10-17 18:06 UTC, greg-in-a-box commented on content/guides/embed/ui-elements/preview.md
> +2. Run `npm i box-ui-elements@15.0.0` to install [BUIE][buie] version with
https://jira.inside-box.net/browse/DDOC-688

2022-10-18 17:25 UTC, greg-in-a-box requested changes
Left a couple comments, everything else looks fine

2022-10-19 17:04 UTC, greg-in-a-box approved these changes

2022-10-27 08:04 UTC, bszwarc approved these changes

2022-10-27 08:10 UTC, merged