DDOC-1057-1061: Formatting fixes, link fixes, note addition
box/developer.box.com pull request #549
Opened 2024-05-15 05:17 UTC by bszwarc

# Description

* Checked links
* Updated message formatting
* Added a note

2024-05-16 12:12 UTC, wsocha approved these changes

2024-05-16 12:14 UTC, wsocha requested changes
Check lint error

2024-06-03 09:18 UTC, SowaProgramuje approved these changes

2024-06-03 09:55 UTC, wsocha approved these changes

2024-06-03 11:12 UTC, merged